/**
 * indexer.job.js
 * Job de indexación proactiva de productos de construcción.
 *
 * Ejecuta scraping en background de forma periódica para una lista curada
 * de los 1000 productos más buscados en el rubro de construcción en Chile,
 * llenando el catálogo sin depender de las búsquedas de usuarios.
 *
 * Uso:
 *   import { iniciarIndexadorProactivo } from './jobs/indexer.job.js';
 *   iniciarIndexadorProactivo(); // Llamar al iniciar el servidor
 */

import { ejecutarScrapingDinamico } from '../services/scraping.service.js';

/**
 * Lista de los 1000 productos más buscados en el rubro de construcción en Chile.
 * Organizados por categoría. Términos reales usados en Sodimac, Construmart, Imperial.
 */
const TERMINOS_INDEXACION = [

  // ══════════════════════════════════════════════════════════
  // CEMENTOS Y ÁRIDOS
  // ══════════════════════════════════════════════════════════
  'cemento melon',
  'cemento polpaico',
  'cemento bio bio',
  'cemento 25 kg',
  'cemento 42 kg',
  'cemento 50 kg',
  'cemento especial',
  'cemento alta resistencia',
  'cemento blanco',
  'cemento refractario',
  'arena gruesa',
  'arena fina',
  'arena silica',
  'arena lavada',
  'grava piedra',
  'gravilla',
  'ripio',
  'piedra chancada',
  'piedra bolón',
  'hormigon premezclado',
  'mortero seco',
  'mortero premezclado',
  'mortero refractario',
  'cal hidratada',
  'cal hidratada saco',
  'cal en pasta',
  'yeso saco',
  'yeso construccion',
  'yeso blanco',
  'yeso moldería',
  'estuco muros',
  'estuco exterior',
  'estuco interior',
  'enfierradura',
  'hormigon celular',
  'hormigon liviano',

  // ══════════════════════════════════════════════════════════
  // FIERROS Y ACERO
  // ══════════════════════════════════════════════════════════
  'varilla corrugada 8mm',
  'varilla corrugada 10mm',
  'varilla corrugada 12mm',
  'varilla corrugada 16mm',
  'varilla corrugada 20mm',
  'varilla corrugada 25mm',
  'varilla lisa 6mm',
  'varilla lisa 8mm',
  'fierro construcción',
  'malla electrosoldada',
  'malla acero c-159',
  'malla acero c-188',
  'malla acero c-257',
  'malla sombra',
  'malla gallinero',
  'malla perimetral',
  'perfil G metalcon',
  'perfil C metalcon',
  'perfil omega metalcon',
  'perfil canal metalcon',
  'perfil H estructural',
  'perfil L angulo',
  'angulo acero 25x25',
  'angulo acero 40x40',
  'angulo acero 50x50',
  'tubo cuadrado acero',
  'tubo redondo acero',
  'planchas acero',
  'barra acero liso',
  'barra acero hexagonal',
  'placa base acero',
  'platina acero',
  'ángulo estructural',

  // ══════════════════════════════════════════════════════════
  // LADRILLOS Y BLOQUES
  // ══════════════════════════════════════════════════════════
  'ladrillo princesa',
  'ladrillo fiscal',
  'ladrillo refractario',
  'ladrillo prensado',
  'ladrillo doble hueco',
  'ladrillo taco',
  'ladrillo artesanal',
  'ladrillo king kong',
  'ladrillo pandereta',
  'bloque hormigon',
  'bloque hormigon 20x20x40',
  'bloque hormigon 15x20x40',
  'bloque hormigon 10x20x40',
  'bloque chimenea',
  'bloque alivianado',
  'bloqueta hormigon',
  'adoquin hormigon',
  'adoquin piso',
  'loseta piso',
  'losa hormigon',

  // ══════════════════════════════════════════════════════════
  // MADERA
  // ══════════════════════════════════════════════════════════
  'tabla madera pino',
  'tabla madera 1x3',
  'tabla madera 1x4',
  'tabla madera 1x6',
  'tabla madera 1x8',
  'tabla madera 2x3',
  'tabla madera 2x4',
  'tabla madera 2x6',
  'tabla madera 2x8',
  'listón madera',
  'listón pino cepillado',
  'listón pino 1x2',
  'viga madera',
  'viga pino 2x4',
  'viga pino 3x3',
  'viga pino 4x4',
  'viga pino 4x6',
  'pino cepillado',
  'pino impregnado',
  'pino radiata',
  'roble madera',
  'madera nativa',
  'madera eucaliptus',
  'madera coigüe',
  'madera álamo',
  'madera mañío',
  'madera ciprés',
  'parquet madera',
  'piso madera flotante',
  'piso madera sólido',
  'deck madera',
  'deck pino impregnado',
  'correa madera',
  'cinta madera',

  // ══════════════════════════════════════════════════════════
  // TABLEROS Y PLANCHAS
  // ══════════════════════════════════════════════════════════
  'terciado estructural',
  'terciado 9mm',
  'terciado 12mm',
  'terciado 15mm',
  'terciado 18mm',
  'terciado pino',
  'terciado fenólico',
  'tablero osb',
  'osb 9mm',
  'osb 11mm',
  'osb 15mm',
  'tablero mdf',
  'mdf 3mm',
  'mdf 6mm',
  'mdf 9mm',
  'mdf 12mm',
  'mdf 15mm',
  'mdf 18mm',
  'melamina blanca',
  'melamina gris',
  'melamina negro',
  'melamina madera',
  'plancha volcanita',
  'volcanita 8mm',
  'volcanita 10mm',
  'volcanita 12mm',
  'plancha fibrocemento',
  'fibrocemento 4mm',
  'fibrocemento 6mm',
  'fibrocemento 8mm',
  'plancha policarbonato',
  'policarbonato alveolar',
  'policarbonato solido',
  'plancha zinc ondulada',
  'plancha acanalada',
  'plancha canvas',
  'plancha pizarreño',
  'plancha ternium',
  'plancha teja',
  'fibraplus',

  // ══════════════════════════════════════════════════════════
  // TECHUMBRES Y CUBIERTA
  // ══════════════════════════════════════════════════════════
  'teja ceramica',
  'teja colonial',
  'teja plana',
  'teja curva',
  'teja andina',
  'teja asfáltica',
  'teja fibrocemento',
  'teja pizarreño',
  'canal lluvia',
  'canal pvc',
  'canal zinc',
  'canal aluminio',
  'cumbrera techo',
  'limahoyo',
  'limatesa',
  'babeta zinc',
  'flashing aluminio',
  'claraboya',
  'tragaluz',
  'ventana techo',
  'nieve antideslizante',
  'fieltro asfaltico',
  'membrana asfaltica',
  'geomembrana',
  'geotextil',
  'impermeabilizante asfáltico',
  'impermeabilizante muros',
  'impermeabilizante techos',
  'espuma poliuretano techo',
  'lana mineral techo',
  'aislante termico lana',
  'aislante termico polystireno',
  'polystireno eps',
  'polystireno xps',
  'polystireno 25mm',
  'polystireno 50mm',
  'polystireno 75mm',

  // ══════════════════════════════════════════════════════════
  // PINTURAS Y REVESTIMIENTOS
  // ══════════════════════════════════════════════════════════
  'pintura latex interior',
  'pintura latex exterior',
  'pintura latex blanco',
  'pintura latex 1 galón',
  'pintura latex 4 litros',
  'pintura latex tina',
  'pintura esmalte',
  'pintura esmalte blanco',
  'pintura esmalte color',
  'pintura esmalte satinado',
  'pintura esmalte brillante',
  'pintura al agua',
  'pintura agua ceresita',
  'pintura agua sipa',
  'pintura agua sayerlack',
  'pintura oleo',
  'barniz madera',
  'barniz marino',
  'barniz transparente',
  'barniz tinte',
  'sellador muros',
  'sellador madera',
  'sellador cemento',
  'sellador fijador',
  'anticorrosivo',
  'pintura anticorrosivo',
  'fondo anticorrosivo',
  'fondo madera',
  'masilla corriente',
  'masilla fina',
  'masilla muro',
  'masilla ceresita',
  'masilla para madera',
  'stucco',
  'impermeabilizante ceresita',
  'ceresita stop agua',
  'membrana liquida',
  'recuplast',
  'tapaporos',
  'aguarrás',
  'thinner',
  'diluyente',
  'removedor pintura',
  'lija hoja',
  'lija madera',
  'lija hierro',
  'lija agua',
  'lija grano 80',
  'lija grano 120',
  'lija grano 220',
  'lija grano 40',

  // ══════════════════════════════════════════════════════════
  // CERÁMICOS, PORCELANATO Y PISOS
  // ══════════════════════════════════════════════════════════
  'porcelanato 60x60',
  'porcelanato 60x120',
  'porcelanato 80x80',
  'porcelanato gris',
  'porcelanato blanco',
  'porcelanato mármol',
  'porcelanato madera',
  'porcelanato antideslizante',
  'ceramica baño',
  'ceramica cocina',
  'ceramica piso',
  'ceramica muro',
  'ceramica 30x30',
  'ceramica 45x45',
  'ceramica 20x20',
  'gres porcelanico',
  'gres rustico',
  'fragua ceramica',
  'adhesivo ceramica',
  'pegamento ceramica',
  'pegamento porcelanato',
  'porcelanato rectificado',
  'ceramica subway',
  'ceramica hexagonal',
  'ceramica esmaltada',
  'azulejo baño',
  'piso vinilico',
  'piso pvc',
  'piso laminado',
  'alfombra piso',
  'tapete vinilico',
  'porcelanato exterior',

  // ══════════════════════════════════════════════════════════
  // HERRAMIENTAS ELÉCTRICAS
  // ══════════════════════════════════════════════════════════
  'taladro percutor',
  'taladro inalámbrico',
  'taladro 12v',
  'taladro 18v',
  'taladro 20v',
  'taladro bosch',
  'taladro makita',
  'taladro dewalt',
  'taladro stanley',
  'taladro bauker',
  'rotomartillo bosch',
  'rotomartillo makita',
  'rotomartillo sds',
  'rotomartillo 800w',
  'rotomartillo 1000w',
  'demoledor neumatico',
  'demoledor eléctrico',
  'amoladora angular',
  'amoladora 4.5 pulgadas',
  'amoladora 7 pulgadas',
  'amoladora 9 pulgadas',
  'amoladora bosch',
  'amoladora makita',
  'amoladora dewalt',
  'sierra circular',
  'sierra circular 7 1/4',
  'sierra circular bosch',
  'sierra circular makita',
  'sierra caladora',
  'sierra caladora bosch',
  'sierra sable',
  'sierra ingletadora',
  'sierra sensitiva',
  'sierra cinta',
  'atornillador inalámbrico',
  'atornillador bosch',
  'atornillador makita',
  'atornillador dewalt',
  'atornillador 12v',
  'atornillador impacto',
  'pistola impacto',
  'llave impacto',
  'lijadora orbital',
  'lijadora de banda',
  'lijadora madera',
  'fresadora madera',
  'router madera',
  'cepillo eléctrico',
  'compresor aire',
  'compresor 25 litros',
  'compresor 50 litros',
  'compresor 100 litros',
  'compresor silencioso',
  'pistola pintura',
  'pistola silicona',
  'pistola clavos',
  'clavadora neumática',
  'engrapadora eléctrica',
  'pistola calor',
  'soplete gas',
  'soldadora mig',
  'soldadora tig',
  'soldadora inverter',
  'soldadora arco',
  'soldadora 130a',
  'soldadora 160a',
  'cortadora plasma',
  'generador eléctrico',
  'generador 2000w',
  'generador 3000w',
  'generador 5000w',
  'generador gasolina',
  'motobomba agua',
  'nivel laser',
  'nivel laser lineas',
  'nivel laser autonivelante',
  'cortadora ceramica',
  'cortadora azulejo',
  'aspiradora obra',
  'aspiradora industrial',
  'pulidora suelos',
  'mezcladora cemento',

  // ══════════════════════════════════════════════════════════
  // HERRAMIENTAS MANUALES
  // ══════════════════════════════════════════════════════════
  'martillo demoledor',
  'martillo carpintero',
  'martillo garra',
  'martillo bola',
  'martillo encofrado',
  'combo 4 libras',
  'combo 8 libras',
  'combo 12 libras',
  'cincel hormigon',
  'cincel acero',
  'cincel plano',
  'puntero albañil',
  'picota punta',
  'pala punta',
  'pala cuchara',
  'pala corazon',
  'huincha medida 5m',
  'huincha medida 7.5m',
  'huincha medida 10m',
  'metro plegable',
  'nivel burbuja 60cm',
  'nivel burbuja 120cm',
  'nivel burbuja 40cm',
  'plomada',
  'escuadra carpintero',
  'escuadra combinada',
  'regla aluminio',
  'serrucho madera',
  'serrucho 22 pulgadas',
  'segueta metal',
  'sierra arco',
  'llave francesa',
  'llave inglesa',
  'llave stilson',
  'llave corona',
  'llave tubo',
  'llave hexagonal',
  'llave mixta',
  'alicate corte',
  'alicate punta',
  'alicate presión',
  'alicate universal',
  'tenaza',
  'destornillador plano',
  'destornillador estrella',
  'destornillador punta',
  'desarmador',
  'cortafríos',
  'tijeras metal',
  'tijeras hojalata',
  'cortadora tubo',
  'espatula albañil',
  'llana acero',
  'llana dentada',
  'llana goma',
  'fratacho esponja',
  'fratacho goma',
  'codal aluminio',
  'plano inclinado',
  'brocha pintura 2 pulgadas',
  'brocha pintura 4 pulgadas',
  'rodillo pintura',
  'rodillo lana',
  'rodillo espuma',
  'bandeja rodillo',
  'extensor rodillo',
  'pistola calafateo',
  'espátula masilla',
  'paleta albanil',
  'paleta puntero',
  'hacha',
  'carretilla obra',
  'carretilla galvanizada',
  'cubeta plastico',
  'balde obra',
  'rastrillo',

  // ══════════════════════════════════════════════════════════
  // GASFITERÍA
  // ══════════════════════════════════════════════════════════
  'tubo pvc 110mm',
  'tubo pvc 50mm',
  'tubo pvc 40mm',
  'tubo pvc 63mm',
  'tubo pvc 25mm',
  'tubo pvc sanitario',
  'tubo pvc hidraulico',
  'tubo cobre 1/2',
  'tubo cobre 3/4',
  'tubo cobre 1 pulgada',
  'tubo ppr 20mm',
  'tubo ppr 25mm',
  'tubo ppr 32mm',
  'codo pvc 90',
  'codo pvc 45',
  'codo pvc 110',
  'codo cobre 1/2',
  'copla pvc',
  'copla cobre',
  'tee pvc',
  'tee cobre',
  'reduccion pvc',
  'sifon pvc',
  'trampa pvc',
  'valvula esfera 1/2',
  'valvula esfera 3/4',
  'valvula esfera 1 pulgada',
  'valvula compuerta',
  'valvula retención',
  'valvula flotador',
  'llave paso agua',
  'llave angular',
  'grifo jardín',
  'grifo exterior',
  'grifería monomando',
  'grifería lavamanos',
  'grifería cocina',
  'grifería ducha',
  'grifería bañera',
  'mezcladora',
  'uniblock',
  'llave de paso salida',
  'flexible metálico 1/2',
  'manguera jardín',
  'manguera 1/2 pulgada',
  'manguera 3/4 pulgada',
  'aspersor riego',
  'gotero riego',
  'bomba agua',
  'bomba sumergible',
  'bomba centrifuga',
  'estanque agua',
  'estanque polietileno 500l',
  'estanque polietileno 1000l',
  'estanque polietileno 2000l',
  'calefon gas',
  'calefon 5 litros',
  'calefon 10 litros',
  'calefon 14 litros',
  'termo acumulacion',
  'termo solar',
  'medidor agua',
  'filtro agua',
  'filtro sedimento',
  'ablandador agua',
  'inodoro wc',
  'inodoro ceramico',
  'inodoro dual',
  'inodoro alargado',
  'taza wc',
  'fluxometro',
  'lavamanos ceramico',
  'lavamanos suspendido',
  'ovalin',
  'tina bañera',
  'tina acrílica',
  'lavaplatos',
  'lavaplatos acero inox',
  'ducha eléctrica',
  'ducha fría',
  'regadera ducha',
  'barra toallero',
  'papelero baño',
  'espejo baño',
  'mueble baño',

  // ══════════════════════════════════════════════════════════
  // ELECTRICIDAD
  // ══════════════════════════════════════════════════════════
  'cable eléctrico 2.5mm',
  'cable eléctrico 4mm',
  'cable eléctrico 6mm',
  'cable eléctrico 1.5mm',
  'cable tierra',
  'cable bipolar',
  'cable goma',
  'cable vulcanizado',
  'cable número 12',
  'cable número 10',
  'cable número 8',
  'cable número 6',
  'cable número 2',
  'interruptor simple',
  'interruptor doble',
  'interruptor triple',
  'interruptor conmutador',
  'interruptor atenuador',
  'enchufe schuko',
  'enchufe toma corriente',
  'enchufe doble',
  'enchufe triple',
  'toma corriente',
  'placa enchufe',
  'ampolleta led',
  'ampolleta led 9w',
  'ampolleta led 12w',
  'ampolleta led e27',
  'ampolleta led gu10',
  'foco empotrar',
  'foco led',
  'foco halogeno',
  'downlight led',
  'panel led',
  'luminaria led',
  'fluorescente led',
  'barra led',
  'tira led',
  'tablero eléctrico',
  'tablero monofasico',
  'tablero bifasico',
  'tablero trifasico',
  'tablero 4 circuitos',
  'tablero 8 circuitos',
  'tablero 12 circuitos',
  'disyuntor 10a',
  'disyuntor 16a',
  'disyuntor 20a',
  'disyuntor 25a',
  'disyuntor 32a',
  'disyuntor diferencial',
  'combinado diferencial',
  'interruptor diferencial',
  'canaleta eléctrica',
  'canaleta 20x12',
  'canaleta 40x25',
  'bandeja cable',
  'tubo conduit',
  'conduit pvc',
  'conduit metálico',
  'unión conduit',
  'caja paso eléctrica',
  'caja profunda',
  'caja octogonal',
  'domino conector',
  'terminal punta',
  'prensacable',
  'cinta aislante',
  'cinta teflon',
  'medidor energia',
  'temporizador',
  'sensor presencia',
  'sensor movimiento',
  'detector humo',
  'alarma incendio',

  // ══════════════════════════════════════════════════════════
  // FIJACIONES
  // ══════════════════════════════════════════════════════════
  'tornillo 1 pulgada',
  'tornillo 2 pulgadas',
  'tornillo 3 pulgadas',
  'tornillo 4 pulgadas',
  'tornillo madera',
  'tornillo metalcon',
  'tornillo drywall',
  'tornillo autoperforante',
  'tornillo galvanizado',
  'tornillo inox',
  'tornillo cabeza plana',
  'tornillo cabeza redonda',
  'clavo 2 pulgadas',
  'clavo 3 pulgadas',
  'clavo 4 pulgadas',
  'clavo galvanizado',
  'clavo hormigon',
  'clavo durock',
  'clavo punta paris',
  'clavo techo',
  'perno hexagonal 1/2',
  'perno hexagonal 3/8',
  'perno hexagonal 1/4',
  'perno ancla',
  'ancla quimica',
  'ancla mecanica',
  'fijacion quimica sika',
  'fijacion quimica fischer',
  'tarugo plastico',
  'tarugo 6mm',
  'tarugo 8mm',
  'tarugo 10mm',
  'tarugo 12mm',
  'tuerca hexagonal',
  'arandela plana',
  'arandela presion',
  'golilla plana',
  'bisagra',
  'bisagra puerta',
  'bisagra mueble',
  'cerradura',
  'cerradura puerta',
  'cerradura dormitorio',
  'cerradura seguridad',
  'cerrojo',
  'manilla puerta',
  'pernio',
  'tirafondo',
  'espárrago',
  'varilla roscada',
  'remache',
  'pop rivet',

  // ══════════════════════════════════════════════════════════
  // ADHESIVOS Y SELLANTES
  // ══════════════════════════════════════════════════════════
  'sika flex',
  'sika boom',
  'sika bond',
  'silicona transparente',
  'silicona blanca',
  'silicona colores',
  'silicona baño',
  'silicona cocina',
  'silicona ácida',
  'silicona neutra',
  'silicona alta temperatura',
  'sellante acrilico',
  'sellante poliuretano',
  'sellante elastomerico',
  'masilla epoxi',
  'resina epoxi',
  'adhesivo contacto',
  'neoprene adhesivo',
  'pegamento pvc',
  'pegamento cemento pvc',
  'adhesivo madera',
  'cola fría',
  'tesa tack',
  'espuma poliuretano',
  'espuma expansiva',
  'espuma sellante',
  'cinta doble faz',
  'cinta masking',
  'cinta americana',
  'cinta vulcanizante',
  'cinta teflon',
  'cinta aislante',
  'sellador juntas',
  'selloextend',
  'butilband',
  'terocal',

  // ══════════════════════════════════════════════════════════
  // PUERTAS Y VENTANAS
  // ══════════════════════════════════════════════════════════
  'puerta madera',
  'puerta mdf',
  'puerta metalica',
  'puerta pvc',
  'puerta vidriada',
  'puerta exterior',
  'puerta interior',
  'puerta corrediza',
  'puerta batiente',
  'marco puerta',
  'marco puerta pino',
  'tapajunta',
  'guarda polvo',
  'ventana aluminio',
  'ventana pvc',
  'ventana corrediza',
  'ventana batiente',
  'ventana guillotina',
  'ventana termopanel',
  'ventana doble vidrio',
  'vidrio templado',
  'vidrio float',
  'vidrio laminar',
  'espejo',
  'cristal ventana',
  'perfiles aluminio',
  'cellosías',
  'persiana',
  'persiana roller',
  'cortina americana',
  'cancela metálica',
  'reja iron',
  'reja tubular',
  'portón metálico',
  'portón corredizo',
  'portón levadizo',
  'baranda acero',
  'baranda aluminio',
  'pasamano',

  // ══════════════════════════════════════════════════════════
  // SEGURIDAD LABORAL
  // ══════════════════════════════════════════════════════════
  'casco seguridad',
  'casco obra',
  'casco blanco',
  'casco amarillo',
  'guantes trabajo',
  'guantes nitrilo',
  'guantes cuero',
  'guantes latex',
  'zapatos seguridad',
  'zapato punta acero',
  'bota caucho',
  'bota pvc',
  'lentes seguridad',
  'antiparras seguridad',
  'antiparras panoramicas',
  'mascara polvo',
  'mascara ffp2',
  'respirador',
  'respirador 3m',
  'tapones oidos',
  'orejeras proteccion',
  'protector auditivo',
  'chaleco reflectante',
  'arnés seguridad',
  'arnés doble gancho',
  'eslinga seguridad',
  'cuerda seguridad',
  'ropa trabajo',
  'pantalon seguridad',
  'chumpa trabajo',
  'delantal cuero',
  'rodillera trabajo',
  'andamio tubular',
  'andamio multidireccional',
  'escalera aluminio',
  'escalera telescopica',
  'escalera plegable',
  'escalera tijera',
  'escalera 8 escalones',
  'escalera 10 escalones',
  'peldaño escalera',
  'caballete madera',
  'borriqueta',
  'señalética obra',
  'cono seguridad',
  'malla seguridad',
  'valla obra',

  // ══════════════════════════════════════════════════════════
  // REVESTIMIENTOS INTERIORES
  // ══════════════════════════════════════════════════════════
  'papel mural',
  'papel mural vinilico',
  'papel mural textura',
  'papel mural moderno',
  'guarda mural',
  'cenefa',
  'estucolux',
  'venecita',
  'piedra decorativa',
  'ladrillo decorativo',
  'piedra laja',
  'piedra cantera',
  'revestimiento piedra',
  'revestimiento madera',
  'lambris madera',
  'machimbre pino',
  'machimbre madera',
  'moldura yeso',
  'moldura decorativa',
  'cornisa yeso',
  'cielorraso',
  'cielo falso',
  'cielo americano',
  'perfil cielorraso',
  'placa cielo americano',
  'perfil tabla yeso',
  'placa tabla yeso',
  'drywall',
  'tabique drywall',
  'volcanita',
  'omega drywall',
  'estructura metalcon',

  // ══════════════════════════════════════════════════════════
  // JARDÍN Y EXTERIOR
  // ══════════════════════════════════════════════════════════
  'manguera jardín 1/2',
  'manguera jardín 3/4',
  'aspersor jardín',
  'regadora jardín',
  'temporizador riego',
  'controlador riego',
  'barrera césped',
  'sustrato jardín',
  'tierra especial',
  'tierra vegetal',
  'compost',
  'abono jardín',
  'fertilizante',
  'herbicida',
  'fungicida',
  'insecticida',
  'cortacésped',
  'bordeadora',
  'podadora',
  'motosierra',
  'soplador hoja',
  'rastrillo jardín',
  'azadón',
  'pala jardín',
  'pala punta',
  'tijera podar',
  'podadora telescópica',
  'separador jardín',
  'borde hormigon',
  'luminaria jardín',
  'poste jardín',
  'macetero hormigon',
  'macetero plastico',
  'muro de contención',
  'gavión',

  // ══════════════════════════════════════════════════════════
  // MAQUINARIA MAYOR
  // ══════════════════════════════════════════════════════════
  'betonera hormigonera',
  'betonera 130 litros',
  'betonera 160 litros',
  'mezcladora mortero',
  'hormigonera electrica',
  'vibradora hormigon',
  'regla vibradora',
  'plancha compactadora',
  'compactadora pata cabra',
  'cortadora asfalto',
  'cortadora de piso',
  'minilift',
  'plataforma elevadora',

];

// ── Control de estado del indexador ──────────────────────────────────────────
let indexadorActivo = false;
let intervalHandle = null;

/**
 * Ejecuta la indexación de un término, con manejo de errores.
 */
const indexarTermino = async (termino) => {
  try {
    console.log(`[Indexador] Indexando: "${termino}"...`);
    const guardados = await ejecutarScrapingDinamico(termino);
    console.log(`[Indexador] "${termino}" completado → ${guardados} productos guardados/actualizados.`);
  } catch (err) {
    console.error(`[Indexador] Error indexando "${termino}":`, err.message);
  }
};

/**
 * Ejecuta UN ciclo completo de indexación de todos los términos,
 * con una pausa de 30 segundos entre cada uno para no saturar el servidor.
 */
const cicloIndexacion = async () => {
  if (indexadorActivo) {
    console.log('[Indexador] Ya hay un ciclo en curso, saltando...');
    return;
  }
  indexadorActivo = true;
  console.log(`[Indexador] ══ Iniciando ciclo de indexación proactiva (${TERMINOS_INDEXACION.length} términos) ══`);

  for (const termino of TERMINOS_INDEXACION) {
    await indexarTermino(termino);
    // Pausa entre términos para no asfixiar Playwright con demasiadas instancias
    await new Promise(resolve => setTimeout(resolve, 30_000));
  }

  console.log('[Indexador] ══ Ciclo completo finalizado ══');
  indexadorActivo = false;
};

/**
 * Inicia el indexador proactivo.
 * - Primer ciclo: se lanza con un delay inicial para no interferir con el arranque del servidor.
 * - Ciclos subsiguientes: cada 6 horas automáticamente.
 *
 * @param {object} opciones
 * @param {number} opciones.delayInicialMs - Milisegundos antes del primer ciclo (default: 2 minutos)
 * @param {number} opciones.intervalHoras - Cada cuántas horas se repite (default: 6 horas)
 */
export const iniciarIndexadorProactivo = ({ delayInicialMs = 2 * 60_000, intervalHoras = 6 } = {}) => {
  const intervalMs = intervalHoras * 60 * 60 * 1000;

  console.log(`[Indexador] Programado: primer ciclo en ${delayInicialMs / 60000} minutos, luego cada ${intervalHoras} horas.`);
  console.log(`[Indexador] Total de términos a indexar: ${TERMINOS_INDEXACION.length}`);

  // Primer ciclo con delay para no interferir con el arranque del servidor
  setTimeout(async () => {
    await cicloIndexacion();
    // Ciclos recurrentes
    intervalHandle = setInterval(cicloIndexacion, intervalMs);
  }, delayInicialMs);
};

/**
 * Detiene el indexador (útil para tests o shutdown graceful).
 */
export const detenerIndexador = () => {
  if (intervalHandle) {
    clearInterval(intervalHandle);
    intervalHandle = null;
    console.log('[Indexador] Detenido.');
  }
};

/**
 * Exporta la lista de términos (útil para tests o inspección).
 */
export { TERMINOS_INDEXACION };
